import type { Metadata } from "next";
import "./globals.css";
import CustomProvider from "@/lib/CustomProvider";
import Header from "@/components/layout/Header";

export const metadata: Metadata = {
  title: "raffle",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <CustomProvider >
      <html lang="en">
      <body className="max-w-screen-2xl mx-auto no-scrollbar flex flex-col">
      <div className=""><Header/></div>
      <div className="pt-16 lg:pt-28">{children}</div>
      </body>
    </html>
    </CustomProvider>
  );
}
